export const SKILL_CATEGORIES = [
  // Technical Skills
  "Frontend Development",
  "Backend Development",
  "Full Stack Development",
  "Mobile Development",
  "DevOps & Infrastructure",
  "Cloud Computing",
  "Database Management",
  "API Development",
  "Web3 & Blockchain",
  "Smart Contracts",
  "DeFi Development",
  "NFT Development",
  "Game Development",
  "AI & Machine Learning",
  "Data Science",
  "Data Analytics",
  "Cybersecurity",
  "Quality Assurance",
  "Software Architecture",
  "System Administration",

  // Design Skills
  "UI/UX Design",
  "Graphic Design",
  "Product Design",
  "Web Design",
  "Mobile App Design",
  "Brand Design",
  "Motion Graphics",
  "3D Design",
  "Illustration",
  "Typography",

  // Business Skills
  "Product Management",
  "Project Management",
  "Business Analysis",
  "Strategy Consulting",
  "Operations Management",
  "Supply Chain Management",
  "Financial Analysis",
  "Investment Banking",
  "Venture Capital",
  "Startup Operations",

  // Marketing Skills
  "Digital Marketing",
  "Content Marketing",
  "Social Media Marketing",
  "SEO/SEM",
  "Email Marketing",
  "Influencer Marketing",
  "Brand Marketing",
  "Performance Marketing",
  "Marketing Analytics",
  "Growth Hacking",

  // Sales Skills
  "Sales Development",
  "Account Management",
  "Business Development",
  "Sales Operations",
  "Customer Success",
  "Lead Generation",
  "Sales Analytics",
  "Channel Partnerships",

  // Other Professional Skills
  "Human Resources",
  "Talent Acquisition",
  "Legal & Compliance",
  "Accounting & Finance",
  "Customer Support",
  "Technical Writing",
  "Content Creation",
  "Video Production",
  "Photography",
  "Translation & Localization",
] as const

export type SkillCategory = (typeof SKILL_CATEGORIES)[number]

export const COUNTRIES = [
  "United States",
  "Canada",
  "United Kingdom",
  "Germany",
  "France",
  "Spain",
  "Italy",
  "Netherlands",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Switzerland",
  "Austria",
  "Belgium",
  "Portugal",
  "Ireland",
  "Australia",
  "New Zealand",
  "Japan",
  "South Korea",
  "Singapore",
  "Hong Kong",
  "India",
  "China",
  "Brazil",
  "Mexico",
  "Argentina",
  "Chile",
  "Colombia",
  "South Africa",
  "Nigeria",
  "Kenya",
  "Egypt",
  "Israel",
  "UAE",
  "Saudi Arabia",
  "Turkey",
  "Russia",
  "Ukraine",
  "Poland",
  "Czech Republic",
  "Hungary",
  "Romania",
  "Bulgaria",
  "Croatia",
  "Estonia",
  "Latvia",
  "Lithuania",
  "Slovenia",
  "Slovakia",
  "Malta",
  "Cyprus",
  "Luxembourg",
  "Iceland",
  "Liechtenstein",
] as const

export type Country = (typeof COUNTRIES)[number]
